#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
05_export_submission_tables.py

Collects CSV outputs into a single Excel file with manuscript-friendly sheet names,
and also creates output/final/ with clearly named CSVs for direct journal submission.

Main tables (manuscript):
- Table 1: Baseline characteristics of ADNI AD participants (n=411) [continuous/descriptive]
- Table 2: Risk stratification summary (analytic sample n=306)
- Table 3: Operating characteristics at thresholds 0.25 / 0.40 / 0.50 (RF, OOF calibrated)
- Table 4: Model performance summary (AUC/Brier/Calibration slope+intercept)

Supplementary tables (provided / referenced):
- Supp Table S1: Confusion matrix at threshold 0.40
- Supp Table S2: Baseline categorical characteristics (n=411)
- Supp Table S3: Additional threshold metrics (0.20/0.30/0.40/0.50/0.60)
- Supp Table S4: Missingness of candidate predictors (n=306)
"""
from pathlib import Path
import pandas as pd

def _need(p: Path) -> Path:
    if not p.exists():
        raise FileNotFoundError(f"Missing required file: {p}")
    return p

def main():
    root = Path(__file__).resolve().parent
    out = root / "output"
    tables_dir = out / "tables"
    final_dir = out / "final"
    tables_dir.mkdir(parents=True, exist_ok=True)
    final_dir.mkdir(parents=True, exist_ok=True)

    # Source CSVs (generated by other scripts)
    table1 = tables_dir / "table1_AD_descriptive_reconstructed.csv"
    table2 = out / "table2_risk_strata.csv"
    table4 = out / "table4_performance_summary.csv"
    threshold = out / "threshold_metrics.csv"

    supp_s1 = out / "SuppTable_S1_confusion_matrix_thr0.40.csv"
    supp_s2 = out / "SuppTable_S2_baseline_categorical_n411.csv"
    supp_s3 = out / "threshold_metrics.csv"  # filter in code
    supp_s4 = out / "SuppTable_S4_missingness_n306.csv"

    # New supplementary tables required by manuscript text
    supp_s5 = out / "SuppTable_S5_sensitivity_ventricles_icv.csv"
    supp_s6 = out / "SuppTable_S6_bootstrap_CI.csv"
    supp_s7 = out / "SuppTable_S7_clinician_cutoffs.csv"
    supp_s8 = out / "SuppTable_S8_net_benefit_key_thresholds.csv"
    supp_s9 = out / "SuppTable_S9_RF_hyperparameters.csv"


    # Build Table 3 from threshold_metrics.csv
    thr_df = pd.read_csv(_need(threshold))
    table3 = thr_df[thr_df["table"].str.lower() == "table3"].copy()
    supp3 = thr_df[thr_df["table"].str.lower().str.contains("supptable")].copy()

    # Read everything
    df_table1 = pd.read_csv(_need(table1))
    df_table2 = pd.read_csv(_need(table2))
    df_table3 = table3.drop(columns=["table"], errors="ignore")
    df_table4 = pd.read_csv(_need(table4))

    df_s1 = pd.read_csv(_need(supp_s1)) if supp_s1.exists() else pd.DataFrame()
    df_s2 = pd.read_csv(_need(supp_s2)) if supp_s2.exists() else pd.DataFrame()
    df_s3 = supp3.drop(columns=["table"], errors="ignore")
    df_s4 = pd.read_csv(_need(supp_s4)) if supp_s4.exists() else pd.DataFrame()

    df_s5 = pd.read_csv(_need(supp_s5)) if supp_s5.exists() else pd.DataFrame()
    df_s6 = pd.read_csv(_need(supp_s6)) if supp_s6.exists() else pd.DataFrame()
    df_s7 = pd.read_csv(_need(supp_s7)) if supp_s7.exists() else pd.DataFrame()
    df_s8 = pd.read_csv(_need(supp_s8)) if supp_s8.exists() else pd.DataFrame()
    df_s9 = pd.read_csv(_need(supp_s9)) if supp_s9.exists() else pd.DataFrame()


    # ---- Write combined Excel ----
    xlsx = final_dir / "Submission_Tables.xlsx"
    with pd.ExcelWriter(xlsx) as writer:
        df_table1.to_excel(writer, sheet_name="Table1", index=False)
        df_table2.to_excel(writer, sheet_name="Table2", index=False)
        df_table3.to_excel(writer, sheet_name="Table3", index=False)
        df_table4.to_excel(writer, sheet_name="Table4", index=False)
        if len(df_s1): df_s1.to_excel(writer, sheet_name="SuppTableS1", index=False)
        if len(df_s2): df_s2.to_excel(writer, sheet_name="SuppTableS2", index=False)
        if len(df_s3): df_s3.to_excel(writer, sheet_name="SuppTableS3", index=False)
        if len(df_s4): df_s4.to_excel(writer, sheet_name="SuppTableS4", index=False)
        if len(df_s5): df_s5.to_excel(writer, sheet_name="SuppTableS5", index=False)
        if len(df_s6): df_s6.to_excel(writer, sheet_name="SuppTableS6", index=False)
        if len(df_s7): df_s7.to_excel(writer, sheet_name="SuppTableS7", index=False)
        if len(df_s8): df_s8.to_excel(writer, sheet_name="SuppTableS8", index=False)
        if len(df_s9): df_s9.to_excel(writer, sheet_name="SuppTableS9", index=False)

    # ---- Also export CSVs with clear names ----
    df_table1.to_csv(final_dir / "Table1.csv", index=False)
    df_table2.to_csv(final_dir / "Table2.csv", index=False)
    df_table3.to_csv(final_dir / "Table3.csv", index=False)
    df_table4.to_csv(final_dir / "Table4.csv", index=False)

    if len(df_s1): df_s1.to_csv(final_dir / "SuppTable_S1.csv", index=False)
    if len(df_s2): df_s2.to_csv(final_dir / "SuppTable_S2.csv", index=False)
    if len(df_s3): df_s3.to_csv(final_dir / "SuppTable_S3.csv", index=False)
    if len(df_s4): df_s4.to_csv(final_dir / "SuppTable_S4.csv", index=False)
    if len(df_s5): df_s5.to_csv(final_dir / "SuppTable_S5.csv", index=False)
    if len(df_s6): df_s6.to_csv(final_dir / "SuppTable_S6.csv", index=False)
    if len(df_s7): df_s7.to_csv(final_dir / "SuppTable_S7.csv", index=False)
    if len(df_s8): df_s8.to_csv(final_dir / "SuppTable_S8.csv", index=False)
    if len(df_s9): df_s9.to_csv(final_dir / "SuppTable_S9.csv", index=False)


    # ---- Write output manifest ----
    manifest = final_dir / "OUTPUT_MANIFEST.md"
    lines = []
    lines.append("# Output manifest (auto-generated)\n")
    lines.append("## Main figures\n")
    for fn in ["Figure1_ROC.png","Figure1_ROC.pdf","Figure2_Calibration.png","Figure2_Calibration.pdf","Figure3_DCA.png","Figure3_DCA.pdf"]:
        p = (out/"figures"/fn)
        if p.exists():
            lines.append(f"- output/figures/{fn}\n")
    lines.append("\n## Supplementary figures\n")
    for fn in ["SuppFigure_S1_RF_feature_importance_top20.png","SuppFigure_S2_risk_strata_distribution.png","SuppFigure_S3_observed_event_rates_by_strata.png","SuppFigure_S4_SHAP_summary_top20.png"]:
        p = (out/"supplementary_figures"/fn)
        if p.exists():
            lines.append(f"- output/supplementary_figures/{fn}\n")
    lines.append("\n## Main tables\n")
    for fn in ["Table1.csv","Table2.csv","Table3.csv","Table4.csv","Submission_Tables.xlsx"]:
        p = final_dir/fn
        if p.exists():
            lines.append(f"- output/final/{fn}\n")
    lines.append("\n## Supplementary tables\n")
    for fn in ["SuppTable_S1.csv","SuppTable_S2.csv","SuppTable_S3.csv","SuppTable_S4.csv","SuppTable_S5.csv","SuppTable_S6.csv","SuppTable_S7.csv","SuppTable_S8.csv","SuppTable_S9.csv"]:
        p = final_dir/fn
        if p.exists():
            lines.append(f"- output/final/{fn}\n")
    manifest.write_text("".join(lines), encoding="utf-8")

    print(f"[OK] Tables exported to: {final_dir}")
    print(f"[OK] Excel bundle: {xlsx}")

if __name__ == "__main__":
    main()